language: node_js
node_js:
- "0.12"
env:
  global:
  - secure: QM1Da3j1fiWEz+fIch6BmvQjg8aunpDfnSDw2uxfdP/oj1ua4mQXokA931sbGhSLrsH6pm43OG60HUoiZ1N5nlVtDPWA4WmQSLvIpteCzaPd0iEABIkfbzPFOqiNNQZkmxXN32zCgKnTYDXD4naoJwmHAlLGjsO9PZi5XqKVD5I=
  - secure: S7ioup+qMNkaTfhIoc2NJBwjZ2f/i6NDI4KgBK/Pc7bZiO1eqj6ZAsczbHXv0CXQIZDnt1PyYcMqUVSheyStWIJsbPHnwQjI3JsraYq/3DDyyr0SqwZaeFCGxtNwqPVveF8+Sq6pXnxRBH2WQqHnCa24Sq8KSw6QUM1EWkrjMKY=
