language: node_js
cache:
  directories:
    - node_modules
node_js:
- '0.12'
env:
  global:
  - secure: bDaTMSBXbp5FS0e4HJKwanQzT6RuKXJoZza/PBFZskbw2RjNcTjfbAyatTIjXEo3eyHLK0gB3X+K5QlnYJPKocYsLzFTKa9FWC5yAkp0czFeMI0RgrEe8lCgQ/0t8bIJAC0MDk3Wi3kNSMfTtzAprHhMs4ZheVDp04Dy14jPIzI=
  - secure: h2AK8jnvNEDiVvjWy+Oc5PNCNp0/ZigZ+7j0mlZyl8hskDVuI0+vj6EwHMi2EXmZBTwUS1ExvpwZKHRelRx5k3MC0DzwTTxgU0mEIGpwQWYqCcxeWUilX8Tu8/PHESL533n0lnJ9hwmG/KZTTGz1nSfxQfotz08w3Egsxk5iDUU=
