ui: tape
browsers:
  - name: chrome
    version: 28..latest
  - name: firefox
    version: 24..latest
  - name: ie
    version: 10..latest
  - name: safari
    version: 6..latest
  - name: ipad
    version: '6.0..latest'
  - name: iphone
    version: '6.0..latest'
  - name: android
    version: '4.0..latest'
